# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'DiscuzMobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # sharesdk 主模块(必须)
  pod 'mob_sharesdk'
  # UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
  pod 'mob_sharesdk/ShareSDKUI'
  # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
  pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
  pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
  #（微信sdk不带支付的命令）
  pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
  # 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
  # 使用配置文件分享模块（非必需）
  # pod 'mob_sharesdk/ShareSDKConfigFile'
  pod 'mob_sharesdk/ShareSDKExtension'
  
  pod 'FMDB'
  pod 'YYKit'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'libPusher'
  pod 'SDWebImage'
  pod 'DTCoreText'
  pod 'MJExtension'
  pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManager'
  pod 'WebViewJavascriptBridge'
  
  # target 'DiscuzMobileTests' do
  # inherit! :search_paths
  # Pods for testing
  # end
  
  # target 'DiscuzMobileUITests' do
  # Pods for testing
  # end
  
end
